(function ensightenInit(){var ensightenOptions = {client: "MSFTsupport", clientId: 1017, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/MSFTsupport/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/MSFTsupport/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Wed Apr 29 09:24:29 GMT 2015", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+
encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=
0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=
a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=
function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};
b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};
b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,
50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};
var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=
log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",
b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=
-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
		
window[ensightenOptions.ns].ensEvent=function(l,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,g){if("[object Array]"===Object.prototype.toString.call(b)){for(var d=0;d<b.length;d++)k.pushTrigger(b[d],g);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof g&&this.queue[b].fn.push(g);return!0},callTrigger:function(b,g,d){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=b.fireOnFirstSet&&g==u||g!=u&&0!=b.fireOnUpdate))for(g=
0;g<b.fn.length;g++)b.fn[g].call(this)},setPollOptions:function(b,g,d){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=g;this.queue[b].fireOnUpdate=d},callPoll:function(b,g,d,l,t){if("string"==typeof b&&g&&g.length&&!(1>g.length)){for(var p=0;p<g.length;p++)k.setPollOptions(g[p],l,t);k.pushWatch(b,g,d)}},pushWatch:function(b,g,d){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,eventArr:[],valueFn:d});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(g);this.pollQueue[b].valueFn=
d},globalWatch:function(){setInterval(function(){for(key in k.pollQueue){var b=k.pollQueue[key],g=b.valueFn(key);if(b.previousVal!==g){for(var d=0;d<b.eventArr.length;d++)k.callTrigger.call(l,b.eventArr[d],b.previousVal,g);k.pollQueue[key].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,g){return k.pushTrigger(b,g)},get:function(b){return k.queue[b]},trigger:function(b,g){return k.callTrigger.call(g||l,b)},poll:function(b,g,d,u,t){t=t||l[ensightenOptions.ns].data.resolve;return k.callPoll(b,
g,t,d,u)}}}(window);
(function(l,u,k){u[l]=k()})("qwery",window[ensightenOptions.ns],function(){function l(){this.c={}}function u(a){return G.g(a)||G.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,e){for(var f=0,c=a.length;f<c;f++)e(a[f])}function b(a){for(var e=[],f=0,c=a.length;f<c;++f)s(a[f])?e=e.concat(a[f]):e[e.length]=a[f];return e}function g(a){for(var e=0,f=a.length,c=[];e<f;e++)c[e]=a[e];return c}function d(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function x(a){return a.match(N)}function t(a,e,f,
c,b,r,h,g,d,k,s){var n,y,l;if(1!==this.nodeType||e&&"*"!==e&&this.tagName&&this.tagName.toLowerCase()!==e||f&&(n=f.match(O))&&n[1]!==this.id)return!1;if(f&&(l=f.match(P)))for(a=l.length;a--;)if(!u(l[a].slice(1)).test(this.className))return!1;if(d&&m.pseudos[d]&&!m.pseudos[d](this,s))return!1;if(c&&!h)for(y in d=this.attributes,d)if(Object.prototype.hasOwnProperty.call(d,y)&&(d[y].name||y)==b)return this;return c&&!q(r,Q(this,b)||"",h)?!1:this}function p(a){return H.g(a)||H.s(a,a.replace(R,"\\$1"))}
function q(a,e,f){switch(a){case "=":return e==f;case "^=":return e.match(w.g("^="+f)||w.s("^="+f,"^"+p(f),1));case "$=":return e.match(w.g("$="+f)||w.s("$="+f,p(f)+"$",1));case "*=":return e.match(w.g(f)||w.s(f,p(f),1));case "~=":return e.match(w.g("~="+f)||w.s("~="+f,"(?:^|\\s+)"+p(f)+"(?:\\s+|$)",1));case "|=":return e.match(w.g("|="+f)||w.s("|="+f,"^"+p(f)+"(-|$)",1))}return 0}function v(a,e){var f=[],b=[],r,h,g,d,m,s=e,n=C.g(a)||C.s(a,a.split(I)),l=a.match(J);if(!n.length)return f;h=(n=n.slice(0)).pop();
n.length&&(r=n[n.length-1].match(K))&&(s=y(e,r[1]));if(!s)return f;d=x(h);g=s!==e&&9!==s.nodeType&&l&&/^[+~]$/.test(l[l.length-1])?function(a){for(;s=s.nextSibling;)1==s.nodeType&&(d[1]?d[1]==s.tagName.toLowerCase():1)&&(a[a.length]=s);return a}([]):s.getElementsByTagName(d[1]||"*");r=0;for(h=g.length;r<h;r++)if(m=t.apply(g[r],d))f[f.length]=m;if(!n.length)return f;k(f,function(a){c(a,n,l)&&(b[b.length]=a)});return b}function c(a,e,f,c){function b(a,c,d){for(;d=S[f[c]](d,a);)if(r(d)&&t.apply(d,x(e[c])))if(c){if(h=
b(d,c-1,d))return h}else return d}var h;return(h=b(a,e.length-1,a))&&(!c||A(h,c))}function r(a,e){return a&&"object"===typeof a&&(e=a.nodeType)&&(1==e||9==e)}function h(a){var e=[],f,c;f=0;a:for(;f<a.length;++f){for(c=0;c<e.length;++c)if(e[c]==a[f])continue a;e[e.length]=a[f]}return e}function s(a){return"object"===typeof a&&isFinite(a.length)}function y(a,e,f){return 9===a.nodeType?a.getElementById(e):a.ownerDocument&&((f=a.ownerDocument.getElementById(e))&&A(f,a)&&f||!A(a,a.ownerDocument)&&E('[id="'+
e+'"]',a)[0])}function m(a,e){var f,c,h;h=e?"string"==typeof e?m(e)[0]:!e.nodeType&&s(e)?e[0]:e:z;if(!h||!a)return[];if(a===window||r(a))return!e||a!==window&&r(h)&&A(a,h)?[a]:[];if(a&&s(a))return b(a);if(f=a.match(T)){if(f[1])return(c=y(h,f[1]))?[c]:[];if(f[2])return g(h.getElementsByTagName(f[2]));if(U&&f[3])return g(h.getElementsByClassName(f[3]))}return E(a,h)}function n(a,e){return function(f){var c,b;L.test(f)?9!==a.nodeType&&((b=c=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),
e(a.parentNode||a,'[id="'+b+'"]'+f,!0),c||a.removeAttribute("id")):f.length&&e(a,f,!1)}}var z=document,D=z.documentElement,E,O=/#([\w\-]+)/,P=/\.[\w\-]+/g,K=/^#([\w\-]+)$/,V=/^([\w]+)?\.([\w\-]+)$/,L=/(^|,)\s*[>~+]/,W=/^\s+|\s*([,\s\+\~>]|$)\s*/g,B=/[\s\>\+\~]/,M=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,R=/([.*+?\^=!:${}()|\[\]\/\\])/g,T=new RegExp(K.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),J=new RegExp("("+B.source+")"+M.source,"g"),I=new RegExp(B.source+
M.source),N=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),S={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,e){return a&&a.parentNode==e.parentNode&&a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,e,f,c){return a?(f=d(a))&&(c=d(e))&&f==c&&f:!1}};l.prototype={g:function(a){return this.c[a]||
void 0},s:function(a,e,f){e=f?new RegExp(e):e;return this.c[a]=e}};var G=new l,H=new l,w=new l,C=new l,A="compareDocumentPosition"in D?function(a,e){return 16==(e.compareDocumentPosition(a)&16)}:"contains"in D?function(a,e){e=9===e.nodeType||e==window?D:e;return e!==a&&e.contains(a)}:function(a,e){for(;a=a.parentNode;)if(a===e)return 1;return 0},Q=function(){var a=z.createElement("p");return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,f){return"class"===f?
a.className:"href"===f||"src"===f?a.getAttribute(f,2):a.getAttribute(f)}:function(a,f){return a.getAttribute(f)}}(),U=!!z.getElementsByClassName,X=z.querySelector&&z.querySelectorAll,Y=function(a,e){var f=[],c,b;try{if(9===e.nodeType||!L.test(a))return g(e.querySelectorAll(a));k(c=a.split(","),n(e,function(a,e){b=a.querySelectorAll(e);1==b.length?f[f.length]=b.item(0):b.length&&(f=f.concat(g(b)))}));return 1<c.length&&1<f.length?h(f):f}catch(r){}return F(a,e)},F=function(a,e){var f=[],c,b,r,d;a=a.replace(W,
"$1");if(c=a.match(V)){d=u(c[2]);c=e.getElementsByTagName(c[1]||"*");b=0;for(r=c.length;b<r;b++)d.test(c[b].className)&&(f[f.length]=c[b]);return f}k(c=a.split(","),n(e,function(a,c,h){d=v(c,a);b=0;for(r=d.length;b<r;b++)if(9===a.nodeType||h||A(d[b],e))f[f.length]=d[b]}));return 1<c.length&&1<f.length?h(f):f},B=function(a){"undefined"!==typeof a.useNativeQSA&&(E=a.useNativeQSA?X?Y:F:F)};B({useNativeQSA:!0});m.configure=B;m.uniq=h;m.is=function(a,e,f){if(r(e))return a==e;if(s(e))return!!~b(e).indexOf(a);
for(var h=e.split(","),d;e=h.pop();)if(d=C.g(e)||C.s(e,e.split(I)),e=e.match(J),d=d.slice(0),t.apply(a,x(d.pop()))&&(!d.length||c(a,d,e,f)))return!0;return!1};m.pseudos={};return m});
(function(){function l(c,b,h){var d;x||(x=window[ensightenOptions.ns].qwery);d=x;if((d=d.call(h,b,h))&&0<d.length){if("_root"==b)c=h;else if(c===h)c=void 0;else{b:{for(var g=d.length,m=0;m<g;m++)if(c===d[m]){d=!0;break b}d=!1}d||(c.parentNode?(t++,c=l(c.parentNode,b,h)):c=void 0)}return c}return!1}function u(c,b,d,g){q[c.id]||(q[c.id]={});q[c.id][b]||(q[c.id][b]={});q[c.id][b][d]||(q[c.id][b][d]=[]);q[c.id][b][d].push(g)}function k(c,b,d,g){if(g||d)if(g)for(var k=0;k<q[c.id][b][d].length;k++){if(q[c.id][b][d][k]===
g){q[c.id][b][d].pop(k,1);break}}else delete q[c.id][b][d];else q[c.id][b]={}}function b(c,b,h){if(q[c][h]){var g=b.target||b.srcElement,k,m,n={},p=m=0;t=0;for(k in q[c][h])q[c][h].hasOwnProperty(k)&&(m=l(g,k,v[c].element))&&d.matchesEvent(h,v[c].element,m,"_root"==k,b)&&(t++,q[c][h][k].match=m,n[t]=q[c][h][k]);b.stopPropagation=function(){b.cancelBubble=!0};for(m=0;m<=t;m++)if(n[m])for(p=0;p<n[m].length;p++){if(!1===n[m][p].call(n[m].match,b)){d.cancel(b);return}if(b.cancelBubble)return}}}function g(c,
g,h,l){function p(c){return function(d){b(m,d,c)}}c instanceof Array||(c=[c]);h||"function"!=typeof g||(h=g,g="_root");var m=this.id,n;for(n=0;n<c.length;n++)q[m]&&q[m][c[n]]||d.addEvent(this,c[n],p(c[n])),l?k(this,c[n],g,h):u(this,c[n],g,h);return this}function d(b,g,h,k){if("string"==typeof b&&"function"==typeof g||"string"==typeof g)d(document).on(b,g,h,k||!1);if(!(this instanceof d)){for(var l in v)if(v[l].element===b)return v[l];p++;v[p]=new d(b,p);v[p]._on=v[p].on;v[p].on=function(b,c,d,g){var h=
"function"==typeof c?c:d;if("function"==typeof c?d:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,d)};return v[p]}this.element=b;this.id=g}var x,t=0,p=0,q={},v={};d.prototype.on=function(b,
d,h){return g.call(this,b,d,h)};d.prototype.off=function(b,d,h){return g.call(this,b,d,h,!0)};d.cancel=function(b){b.preventDefault();b.stopPropagation()};d.addEvent=function(b,d,g){b.element.addEventListener(d,g,"blur"==d||"focus"==d)};d.matchesEvent=function(){return!0};d.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||
""),750)};window[ensightenOptions.ns].Delegate=d})();(function(l){var u=l.addEvent;l.addEvent=function(k,b,g){if(k.element.addEventListener)return u(k,b,g);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+b,g)};l.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}})(window[ensightenOptions.ns].Delegate);window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate;
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_CAPI_LOC="//premieruat.microsoft.com/scripts/wt_capi.js";var REGEX_MPO_STG={r:/\/premieruat\.microsoft\.com/i};var REGEX_MPO_INCIDENT_SUBMIT={r:/\/Incident\/Submit(|\/)$/i};var mpoTPageArray=[REGEX_MPO_STG];var HTMLPATH="/HTML/BODY";Bootstrapper.MVT.isMPOStagTestPage=false;function isValidLang(){var isValidLangFlag=true;return isValidLangFlag}if(REGEX_MPO_STG.r.test(window.location.href)&&
isValidLang()&&Bootstrapper.MVT.isTestmode(REGEX_MPO_STG)){Bootstrapper.MVT.isMPOStagTestPage=true;Bootstrapper.MVT.push({x:HTMLPATH,t:"wt",base:REGEX_CAPI_LOC,o:{"s_pageTimeout":6E3}});Bootstrapper.MVT.setWTOEvents()}else if(REGEX_MPO_STG.r.test(document.URL))Bootstrapper.MVT.onWTOError(null)},784119,[770194],306226,[255984]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var SSB_STAG={"r":/\/stg-smallbusiness\.support\.microsoft\.com/i,"u":"//stg-smallbusiness.support.microsoft.com/AB/wt_capi.js"};var SMC_DEV={"r":/\/msssmctwb02\.redmond\.corp\.microsoft\.com/i,"u":"//msssmctwb02.redmond.corp.microsoft.com/my/scripts/wt_capi.js"};var SMC_UAT={"r":/\/(support-test|support-uat|support-stg|support-uat2)\.microsoft\.com/i,"u":"/library/javascript/abtest/wt_capi.js"};
var DEV_SMC={"r":/support-uat\.microsoft\.com\/[a-z]{2}-[a-z]{2}\/contactus/i,"u":"//support-uat.microsoft.com/my/scripts/wt_capi.js"};var REGEX_OASP_HANDLER={u:/\/oas\/oasp_handler/i,i:/techsupport|upandrunning/i};var testconfig=[SMC_DEV,SMC_UAT,DEV_SMC];var HTMLPATH="/HTML/BODY";Bootstrapper.MVT.isStagTestPage=false;function onWTOError(evt){var error="invalid";try{if(evt)error=evt.name+"_"+evt.state}catch(e){}var meta=document.createElement("meta");meta.name="wtoexp";meta.content=error;document.getElementsByTagName("head")[0].appendChild(meta)}
function setWTOEvents(){if(typeof WTOptimize=="undefined")setTimeout(function(){setWTOEvents()},10);else{WTOptimize.addEventHandler(WTEvent.INVALID,onWTOError);WTOptimize.addEventHandler(WTEvent.ABORT,onWTOError);WTOptimize.addEventHandler(WTEvent.DONE,null,onWTOError);WTOptimize.addEventHandler(WTEvent.PAGEVIEW,null,onWTOError)}}function isEnUs(){var isValidLang=true;try{var langLoc=document.getElementsByTagName("html")[0].getAttribute("lang")||"";langLoc=langLoc.toLocaleLowerCase();isValidLang=
!!(","+"en-us").indexOf(langLoc);if(!isValidLang){var classList=document.getElementsByTagName("body")[0].getAttribute("class")||"";classList=classList.toLocaleLowerCase();isValidLang=!!(","+classList).indexOf("en-us")}}catch(e){}return isValidLang}function isAgentPage(){var _isAgentPage=true;if(REGEX_OASP_HANDLER.u.test(window.location.pathname)){_isAgentPage=false;var metaCollection=document.getElementsByTagName("meta");try{for(var j=0;j<metaCollection.length;j++)if(metaCollection[j].getAttribute("name")==
"ms.sup_cid"&&metaCollection[j].getAttribute("content").indexOf("Agentpage")>-1)_isAgentPage=true}catch(e){}}return _isAgentPage}function isTestPage(){var _isTestPage=false;for(var i=0;i<testconfig.length;i++)if(testconfig[i].r.test(document.URL))_isTestPage=true;return _isTestPage}function getCapiURL(){var _capiUrl;for(var i=0;i<testconfig.length;i++)if(testconfig[i].r.test(document.URL))_capiUrl=testconfig[i].u;return _capiUrl}function preProcessWTOTest(){var _preProcessWTO=true;try{if(isEnUs()){var regex_oasp_tech=
/((\/oas\/oasp_handler)|(\/(getsupport|(getsupport\/hostpage.aspx))))/i;var regex_oasp_tech_qs=/wfname=(techsupport|upandrunning)/i;if(regex_oasp_tech.test(location.pathname)&&regex_oasp_tech_qs.test(location.search)){var exemptProd=/((gsacn=12840)|(gsacn=17146)|(gsacn=17405)|(gsacn=17402))/i.test(location.href);if(exemptProd){document.cookie="GetSup-WTO-AgentPage-Flight2\x3d; domain\x3dmicrosoft.com; path\x3d/";_preProcessWTO=false}}if(/\/ContactUs\/(TechnicalSupport|SetupAndInstallation).*/i.test(location.pathname)){var ab_cookie=
Bootstrapper.Cookies.get("GetSup-WTO-AgentPage-Flight2");if(ab_cookie==undefined||ab_cookie==null||ab_cookie==1)document.cookie="GetSup-WTO-AgentPage-Flight2\x3d2; domain\x3dmicrosoft.com; path\x3d/"}if(regex_oasp_tech.test(location.pathname)&&regex_oasp_tech_qs.test(location.search))Bootstrapper.bindDOMParsed(function(){var REGEX_AGENT=/agent/i;var REGEX_PID=/pid/i;var sup_cid=$("meta[name\x3dms.sup_cid]").attr("content");if(!REGEX_AGENT.test(sup_cid)||REGEX_PID.test(sup_cid))if($(".heroSection .abflight",
window.parent.document).length>0)$(".heroSection",window.parent.document).hide()})}else document.cookie="GetSup-WTO-AgentPage-Flight2\x3d1; domain\x3dmicrosoft.com; path\x3d/"}catch(err){}return _preProcessWTO}if(isTestPage()&&preProcessWTOTest()&&isEnUs()){var capi=getCapiURL();if(~window.location.href.indexOf("testmode\x3dtrue")){Bootstrapper.MVT.isStagTestPage=true;Bootstrapper.MVT.push({x:HTMLPATH,t:"wt",base:capi,o:{"s_pageTimeout":6E3}});setWTOEvents()}else onWTOError(null)}},767665,[770194],
256092,[255984]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_SUP_PROD={r:/\/(support|support2)\.microsoft\.com/i};var REGEX_CNTUS={u:/\/contactus(|\/)$/i,ln:/(en-(us|au|ca|ie|nz|za|gb)|cs-cz)/i};var REGEX_HOMEPG={u:/^\/(|default\.aspx)$/i,e:/kb|gp|error|scid/i,ln:/ln=(en-gb|ja|de)/i};var REGEX_PROD_HUB={u:/\/product\/(windows|office|internet-explorer)/i};var REGEX_CNTUS_TECH_SETUP={u:/(\/(contactus|contactussupport)\/(technicalsupport|setupandinstallation))(|\/)$/i};var REGEX_OASP_HANDLER=
{u:/\/oas\/oasp_handler/i,i:/techsupport|upandrunning/i};var REGEX_GETSUPP={u:/\/(getsupport|(getsupport\/hostpage.aspx))/i,i:/techsupport|upandrunning/i};var REGEX_SEARCHPG={u:/\/search(|\/.*)/i};var REGEX_SOLUTIONPG={u:/\/solutions\/(windows|office|internet-explorer)\/.*/i};var REGEX_KB_LNSAT={u:/kb\/(929135|929833|2872074|2952664|3003057|318378|947821|923737|2847882|2987107|2734782|2739501|2399238|322389|2696484|950929|290301|976932|322756|912265|883260|318380|824684|971058|3003743|2899270|2409098|2652320|314060|829918|2993958|3000988|956196|2991963|3002885|2730071|2608523|316992|2681286|949104|949358|2715633|308260|3010788|2520970|2438651|890830|2741355|929833|2741355)/i};
var REGEX_KB_HNSAT={u:/kb\/(3000850|3011780|2830477|3008627|2673774|2992611|2665946|2995388|3016338|179113|2574819|917607|827218|126449|947215|2919355|2994375|2592687|2977218|2998527|2019667|2903984|2994023|2970228|3000853|3003667|3001554|290846|971606|3009008|3000850|2985461|316951|2978092|2975719|2923545|2458544|2976536|290938|2719662|3006226|2665750|979665|2977728|2670838|909604|310049|2990967|2118008|3008188)/i};var REGEX_FLIGHT_14_LANG=/en-us/i;var REGEX_BC_OASP_HANDLER={u:/\/oas\/oasp_handler/i,
i:/tenant.*ClassicCommercial/i,e:/sd\=partner/i,p:/pesid.*(14566|14577|14544|14645|15044|14555|14590|15432|15433|15430|15435|15436|15431|15434|14910|13023|13022|13265|13020|13028|15243|15244|15245|15242|14856|14842|14843|14844|14845|12096|12250|12095|12248|12097|12094|12249|12098|15200|15201|15196|15195|15197|15298|14915|14898|15210|14517|15211|15214|14490|15212|14529)/i};var pageArray=[REGEX_CNTUS,REGEX_BC_OASP_HANDLER,REGEX_PROD_HUB,REGEX_SEARCHPG,REGEX_SOLUTIONPG,REGEX_KB_LNSAT,REGEX_KB_HNSAT,
REGEX_HOMEPG];Bootstrapper.MVT.isTestPage=false;function checkEnUsForAgentPage(){var isValidLang=true;try{var langLoc=document.getElementsByTagName("html")[0].getAttribute("lang")||"";langLoc=langLoc.toLocaleLowerCase();isValidLang=langLoc.match(/en-us/i)!==null;if(!isValidLang){var classList=document.getElementsByTagName("body")[0].getAttribute("class")||"";classList=classList.toLocaleLowerCase();isValidLang=langLoc.match(/en-us/i)!==null}}catch(e){}return isValidLang}function isValidPesId(){var _isValidPesid=
false;var querystr=window.location.search;if(REGEX_BC_OASP_HANDLER.i.test(querystr))_isValidPesid=REGEX_BC_OASP_HANDLER.p.test(querystr);return _isValidPesid}function isTestStepinWF(langLoc,val){var _isSupCid=false;var _isValidLang=false;var classList=document.getElementsByTagName("body")[0].getAttribute("class")||"";classList=classList.toLocaleLowerCase();_isValidLang=REGEX_FLIGHT_14_LANG.test(langLoc)||REGEX_FLIGHT_14_LANG.test(classList);var metaCollection=document.getElementsByTagName("meta");
try{for(var j=0;j<metaCollection.length;j++)if(metaCollection[j].getAttribute("name")=="ms.sup_cid"&&metaCollection[j].getAttribute("content").toLowerCase().indexOf(val)>-1)_isSupCid=true}catch(e){}return _isSupCid&&_isValidLang}function isTestPage(){var _isTp=false;var urlpath=window.location.pathname;var querystr=window.location.search;var isqueryexcl,isqueryincl;var langLoc=document.getElementsByTagName("html")[0].getAttribute("lang")||"";langLoc=langLoc.toLowerCase();var isValidLang="en-us"==
langLoc;for(var i=0;i<pageArray.length;i++){isqueryexcl=pageArray[i].e?pageArray[i].e.test(querystr):false;isqueryincl=pageArray[i].i?pageArray[i].i.test(querystr):true;if(pageArray[i].u.test(urlpath)&&!isqueryexcl&&isqueryincl)_isTp=true;if(REGEX_HOMEPG.u.test(urlpath)&&pageArray[i].ln&&pageArray[i].ln.test(querystr))isValidLang=true;else if(REGEX_CNTUS.u.test(urlpath)&&pageArray[i].ln&&pageArray[i].ln.test(urlpath))isValidLang=true;if(/windows-10-technical-preview/i.test(urlpath))_isTp=false}if(REGEX_OASP_HANDLER.u.test(window.location.pathname))if(REGEX_OASP_HANDLER.i.test(querystr))isValidLang=
isTestStepinWF(langLoc,"agentpage");else if(REGEX_BC_OASP_HANDLER.i.test(querystr))isValidLang=isValidPesId()&&(isTestStepinWF(langLoc,"select_issue")||isTestStepinWF(langLoc,"problem_description"));return REGEX_SUP_PROD.r.test(document.URL)&&_isTp&&isValidLang}function isTestmode(){return REGEX_SUP_PROD.r.test(document.URL)&&~window.location.href.indexOf("testmode\x3dtrue")}function setWinnerForAgentFlight(){var _isFlightTestPage=false;try{if(checkEnUsForAgentPage()){var regex_oasp_tech=/((\/oas\/oasp_handler)|(\/(getsupport|(getsupport\/hostpage.aspx))))/i;
var regex_oasp_tech_qs=/wfname=(techsupport|upandrunning)/i;if(REGEX_CNTUS_TECH_SETUP.u.test(location.pathname)||regex_oasp_tech.test(location.pathname)&&regex_oasp_tech_qs.test(location.search)){document.cookie="GetSup-WTO-AgentPage-Flight2\x3d5; domain\x3dmicrosoft.com; path\x3d/";_isFlightTestPage=true}if(regex_oasp_tech.test(location.pathname)&&regex_oasp_tech_qs.test(location.search)){var exemptProd=/((gsacn=12840)|(gsacn=17146)|(gsacn=17405)|(gsacn=17402))/i.test(location.href);if(exemptProd){document.cookie=
"GetSup-WTO-AgentPage-Flight2\x3d; domain\x3dmicrosoft.com; path\x3d/";_isFlightTestPage=false}}if(_isFlightTestPage){var meta=document.createElement("meta");meta.name="ms.eguid";meta.content="018.E";document.getElementsByTagName("head")[0].appendChild(meta)}}else{document.cookie="GetSup-WTO-AgentPage-Flight2\x3d1; domain\x3dmicrosoft.com; path\x3d/";_isFlightTestPage=false}}catch(err){}}if(isTestPage()||Bootstrapper.MVT.isTestmode(REGEX_SUP_PROD)){Bootstrapper.MVT.isTestPage=true;Bootstrapper.MVT.push({x:"/HTML/BODY",
t:"wt",base:"/library/javascript/abtest/wt_capi.js",o:{"s_pageTimeout":6E3}});Bootstrapper.MVT.setWTOEvents()}else if(REGEX_SUP_PROD.r.test(document.URL)){Bootstrapper.MVT.onWTOError(null);setWinnerForAgentFlight()}},798274,[770194],256095,[255984]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.TAG={_ns:"bi"};Bootstrapper.TAG.getMeta=function(mn){var m=document.getElementsByTagName("meta");for(var i in m)if(m[i].name==mn)return m[i].content;return""};Bootstrapper.TAG.setMeta=function(mn,mv){var m=document.getElementsByTagName("meta");var exists=false;for(var i in m)if(m[i].name==mn){m[i].content=mv;exists=true}if(!exists)Bootstrapper.TAG.appendCustomMeta(mn,
mv)};Bootstrapper.TAG.appendCustomMeta=function(tn,tv){var meta;var appendTarget=document.getElementsByTagName("head").item(0);if(document.createElement&&(meta=document.createElement("meta"))){meta.name=tn;meta.content=tv;appendTarget.appendChild(meta)}};Bootstrapper.TAG.removeMeta=function(mn){var m=document.getElementsByTagName("meta");var meta;for(var i in m)if(m[i].name==mn){meta=m[i];break}if(meta&&typeof meta=="object"){var par=meta.parentElement||meta.parentNode;par.removeChild(meta)}};Bootstrapper.TAG.getAttr=
function(el,an){if($)return $(el).attr(an);else if(typeof el=="object")return el.getAttribute(an);else return document.getElementById(el).getAttribute(an);return""};Bootstrapper.TAG.setAttr=function(el,an,av){try{if($)$(el).attr(an,av);else if(typeof el=="object")el.setAttribute(an,av);else document.getElementById(el).setAttribute(an,av);return true}catch(err){return false}};Bootstrapper.TAG.getQueryValue=function(name,url){try{name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?\x26]"+
name+"\x3d([^\x26#]*)");var results=regex.exec(url);return results==null?"":decodeURIComponent(results[1].replace(/\+/g," "))}catch(err){return""}};Bootstrapper.TAG.getLinkBITitle=function(elem,defvalue){try{var ti=$(elem).attr("bi:title");if(ti==null||ti.indexOf("/")>-1||ti.toLowerCase().indexOf("javascript:")>-1||$.trim(ti).length<1)if(defvalue==null||defvalue==undefined||defvalue.length<1)ti=$.trim($(elem).text())||$(elem).attr("title")||$("IMG",elem).length>0&&$("IMG",elem).attr("alt")||"";else ti=
defvalue;ti=$.trim(ti).toLowerCase();return ti}catch(err){return""}};Bootstrapper.TAG.isMSIE11Plus=function(){try{return navigator.userAgent.indexOf("MSIE")>-1&&!(navigator.userAgent.indexOf("MSIE 10")>-1)&&navigator.userAgent.indexOf("MSIE 1")>-1}catch(err){return""}};Bootstrapper.TAG.setChannelServicesVisitId=function(){try{if(typeof awasaServicesFacade!=="undefined"){if(awasaServicesFacade.getVisitId()!="00000000-0000-0000-0000-000000000000")Bootstrapper.TAG.ChannelVisitID=awasaServicesFacade.getVisitId()}else Bootstrapper.TAG.ChannelVisitID=
Bootstrapper.Cookies.get("awasaVisit")}catch(err){}};Bootstrapper.TAG.TriggerWEDCSContentLoad=function(params){try{if(params==undefined||params==null)return false;if(typeof MscomCustomEvent=="function"&&Bootstrapper.TMDL.collectors.WEDCS._page_load)MscomCustomEvent.apply(this,params);else Bootstrapper.TMDL.collectors.WEDCS.postWEDCSLoad(function(p_params){return function(){try{MscomCustomEvent.apply(this,params)}catch(err){}}}(params))}catch(err){Bootstrapper.reportException(err);return false}};Bootstrapper.TAG.getURLLocation=
function(url){try{var urlloc=document.createElement("a");urlloc.href=url;return urlloc}catch(err){Bootstrapper.reportException(err);return false}}},716839,255874);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_CAPI_LOC="//stg-smallbusiness.support.microsoft.com/AB/wt_capi.js";var REGEX_SSB_STG={r:/\/\/stg-smallbusiness\.support\.microsoft\.com/i};var REGEX_SSB_HOMEPG={r:/en-us(|\/|\/home(|\/))$/i};var REGEX_SSB_GLOBAL_HOMEPG={r:/\/[a-z]{2}-[a-z]{2}(|\/|\/home(|\/))$/i};var REGEX_SSB_CONTACT={r:/en-us\/contact(|\/)$/i};var REGEX_SSB_SEARCH_RESULTS={r:/en-us\/search|dynamicsearch(|\/)$/i};
var ssbTPageArray=[REGEX_SSB_STG];var HTMLPATH="/HTML/BODY";Bootstrapper.MVT.isSsbStagTestPage=false;function isValidLang(){var isValidLangFlag=false;var urlpath=window.location.pathname;try{var langLoc=document.getElementsByTagName("html")[0].getAttribute("lang")||"";langLoc=langLoc.toLowerCase();isValidLangFlag=",en-us".indexOf(langLoc)>0;for(var i=0;i<ssbTPageArray.length;i++)if(ssbTPageArray[i].r.test(urlpath)){isValidLangFlag=true;break}}catch(e){}return isValidLangFlag}if(REGEX_SSB_STG.r.test(window.location.href)&&
isValidLang()&&Bootstrapper.MVT.isTestmode(REGEX_SSB_STG)){Bootstrapper.MVT.isSsbStagTestPage=true;Bootstrapper.MVT.push({x:HTMLPATH,t:"wt",base:REGEX_CAPI_LOC,o:{"s_pageTimeout":6E3}});Bootstrapper.MVT.setWTOEvents()}else if(REGEX_SSB_STG.r.test(document.URL))Bootstrapper.MVT.onWTOError(null)},773781,[770194],300589,[255984]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.trackerFramework=function(){cArray=function(){var funcs=[],hasRun=false;return{clear:function(){funcs=[]},add:function(f){if(hasRun){try{f()}catch(e){Bootstrapper.reportException(e)}return}if(typeof f!=="function")return;funcs[funcs.length]=f},exec:function(){var toRun=funcs,i,len;hasRun=true;for(i=0,len=toRun.length;i<len;i++)try{toRun[i].call(window)}catch(e){Bootstrapper.reportException(e)}},
haveRun:function(){return hasRun},getFuncs:function(){return funcs}}};return{prePopulate:cArray(),postPopulate:cArray(),globalData:cArray(),localData:cArray(),globalEvents:cArray(),localEvents:cArray(),execute:function(){this.prePopulate.exec();this.events=this.getEvents();this.postPopulate.exec();this.target.t()},getData:function(){var retObj={};var localFuncs=this.localData.getFuncs();for(var i=0,l=localFuncs.length;i<l;i++){var tempObj=localFuncs[i].call(window);for(key in tempObj)if(tempObj[key])retObj[key]=
tempObj[key]}this.localDataObj={};for(key in retObj)this.localDataObj[key]=retObj[key];var globalFuncs=this.globalData.getFuncs();for(var i=0,l=globalFuncs.length;i<l;i++){var tempObj=globalFuncs[i].call(window);for(key in tempObj)if(tempObj[key])retObj[key]=tempObj[key]}return retObj},getEvents:function(){var retEvents="";var globalFuncs=this.globalEvents.getFuncs();for(var i=0,l=globalFuncs.length;i<l;i++){var temp=globalFuncs[i].call(window);retEvents+=retEvents!=""?","+temp:temp}var localFuncs=
this.localEvents.getFuncs();for(var i=0,l=localFuncs.length;i<l;i++){var temp=localFuncs[i].call(window);retEvents+=retEvents!=""?","+temp:temp}return retEvents},autoLaunch:function(){this.target=window.s;this.dataLayer=this.getData();this.execute()}}}()},457210,255721);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;document._write=document.write;document.write=function(x){if(Bootstrapper.hasDOMParsed()&&document.getElementsByTagName("html").length&&document.getElementsByTagName("html")[0].innerHTML.match(/\<\/body/i)){var d=document.getElementById("jsPlaceHolder");if(d===null){d=document.createElement("div");d.style.display="none";d.style.height=0;d.style.width=0;d.id="jsPlaceHolder"}x=
x.split(/\<script/i);var scripts=[];var repSpans=[];var repScripts=[];if(x[0]=="")x.shift();for(var i=0;i<x.length;i++){x[i]=x[i].split(/\/script\>/i);if(x[i][0].indexOf("\x3c")){scripts.push("\x3cscript"+x[i][0]+"/script\x3e");x[i][0]="\x3cspan name\x3d'ensScript'\x3e\x3c/span\x3e"}x[i]=x[i].join("")}x=x.join("");d.innerHTML=x;var spans=d.getElementsByTagName("span");for(var i=0;i<spans.length;i++)if(spans[i].getAttribute("name")=="ensScript"){var s=scripts.shift();s=s.replace(/\<\/script\>/i,"");
s=s.replace(/\s"/g,'"');s=s.split("\x3e");var attr=s[0].split(" ");var script=document.createElement("script");for(var j=1;j<attr.length;j++){attr[j]=attr[j].split("\x3d");var attrName=attr[j].shift();attr[j]=attr[j].join("\x3d");if(attr[j].match(/^(\'|\")/)){var wrapper=attr[j].slice(0,1);attr[j]=attr[j].slice(1,attr[j].length);attr[j]=attr[j].slice(0,attr[j].lastIndexOf(wrapper))}script.setAttribute(attrName,attr[j]);script.text=s[1]}repSpans.push(spans[i]);repScripts.push(script)}for(var i=repSpans.length-
1;i>=0;i--)d.replaceChild(repScripts[i],repSpans[i]);document.body.appendChild(d)}else document._write(x)};Bootstrapper.linkTrack=function(e,fn){Bootstrapper.unobtrusiveAddEvent(e,"onclick",fn)};Bootstrapper.getElementsByClassName=function(d,c,f){x=arguments.length>1?arguments.length==2?typeof arguments[1]=="object"&&arguments[1]!=null?c:document:c:document;y=arguments.length>1?arguments.length==2?typeof arguments[1]=="boolean"?c:false:f:false;var e=[];x=typeof x=="object"?x:document;for(var b=x.getElementsByTagName("*"),
a=0,g=b.length;a<g;a++)(!y&&b[a].className==d||y&&~b[a].className.indexOf(d))&&e.push(b[a]);return e};Bootstrapper.Cookies=new function(){this.defaultDomain="."+window.location.hostname.match(/[-\w]+\.(?:[-\w]+\.xn--[-\w]+|[-\w]{3,}|[-\w]+\.[-\w]{2})$/i)[0];this._cookies={};this.build=function(){for(var c=document.cookie.split("; "),a=0;a<c.length;a++)this._cookies[c[a].slice(0,c[a].indexOf("\x3d"))]=c[a].slice(c[a].indexOf("\x3d")+1)};this.get=function(c,a,f){this.build();var g=this._cookies[c];
if(arguments.length==1)return g;else for(var g=g.split(f||"\x26"),d=0,b=g.length;d<b;d++)if(g[d].indexOf(a+"\x3d")==0)return g[d].slice((a+"\x3d").length,g[d].length)};this.modCookie=function(c,a,f,g){document.cookie=c+"\x3d"+a+(f?";expires\x3d"+f:"")+";domain\x3d"+(g?g:this.defaultDomain)};this.set=function(c,a,f,g){if(arguments.length==4){for(var d="",b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");this.modCookie(c,d,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){d=
"";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d,f)}else{d="";for(b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a,f);else if(typeof a=="object"){d="";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a)};this.addValue=function(c,a,f,g){this.build();var d=this._cookies[c]||"";if(arguments.length==4){for(var b="",e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");
this.modCookie(c,d+b,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");this.modCookie(c,d+b,f)}else{b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");this.modCookie(c,d+b)}else this.modCookie(c,d+a,f);else if(typeof a=="object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");this.modCookie(c,d+b)}else this.modCookie(c,d+a)};this.remove=function(c,a){this.build();
if(this._cookies[c]){var f=(new Date).toGMTString();this.modCookie(c,"",f,a)}};this.check=function(c,a){this.build();return arguments.length==2?this.get(c).match(a+"\x3d")?!0:!1:this._cookies[c]?!0:!1};this.build()};Bootstrapper.Cookies=new function(){this.defaultDomain="."+window.location.hostname.match(/[-\w]+\.(?:[-\w]+\.xn--[-\w]+|[-\w]{3,}|[-\w]+\.[-\w]{2})$/i)[0];this._cookies={};this.build=function(){for(var c=document.cookie.split("; "),a=0;a<c.length;a++)this._cookies[c[a].slice(0,c[a].indexOf("\x3d"))]=
c[a].slice(c[a].indexOf("\x3d")+1)};this.get=function(c,a,f){this.build();var g=this._cookies[c];if(arguments.length==1)return g;else for(var g=g.split(f||"\x26"),d=0,b=g.length;d<b;d++)if(g[d].indexOf(a+"\x3d")==0)return g[d].slice((a+"\x3d").length,g[d].length)};this.modCookie=function(c,a,f,g){document.cookie=c+"\x3d"+a+(f?";expires\x3d"+f:"")+";domain\x3d"+(g?g:this.defaultDomain)};this.set=function(c,a,f,g){if(arguments.length==4){for(var d="",b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");
this.modCookie(c,d,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){d="";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d,f)}else{d="";for(b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a,f);else if(typeof a=="object"){d="";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a)};this.addValue=function(c,a,f,g){this.build();var d=this._cookies[c]||
"";if(arguments.length==4){for(var b="",e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");this.modCookie(c,d+b,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");this.modCookie(c,d+b,f)}else{b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");this.modCookie(c,d+b)}else this.modCookie(c,d+a,f);else if(typeof a=="object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");
this.modCookie(c,d+b)}else this.modCookie(c,d+a)};this.remove=function(c,a){this.build();if(this._cookies[c]){var f=(new Date).toGMTString();this.modCookie(c,"",f,a)}};this.check=function(c,a){this.build();return arguments.length==2?this.get(c).match(a+"\x3d")?!0:!1:this._cookies[c]?!0:!1};this.build()};window.BrowserDetect={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||
"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(b){for(var a=0;a<b.length;a++){var c=b[a].string,d=b[a].prop;this.versionSearchString=b[a].versionSearch||b[a].identity;if(c){if(-1!=c.indexOf(b[a].subString))return b[a].identity}else if(d)return b[a].identity}},searchVersion:function(b){var a=b.indexOf(this.versionSearchString);if(-1!=a)return parseFloat(b.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",
identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},
{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",
identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};BrowserDetect.init();(function(){var BufferClass=typeof Buffer=="function"?Buffer:Array;var _buf=new BufferClass(16);var toString=[];var toNumber={};for(var i=0;i<256;i++){toString[i]=(i+256).toString(16).substr(1);toNumber[toString[i]]=i}function parse(s){var buf=new BufferClass(16);var i=0,ton=toNumber;s.toLowerCase().replace(/[0-9a-f][0-9a-f]/g,function(octet){buf[i++]=toNumber[octet]});return buf}function unparse(buf){var tos=
toString,b=buf;return tos[b[0]]+tos[b[1]]+tos[b[2]]+tos[b[3]]+"-"+tos[b[4]]+tos[b[5]]+"-"+tos[b[6]]+tos[b[7]]+"-"+tos[b[8]]+tos[b[9]]+"-"+tos[b[10]]+tos[b[11]]+tos[b[12]]+tos[b[13]]+tos[b[14]]+tos[b[15]]}var b32=4294967296,ff=255;function uuid(fmt,buf,offset){var b=fmt!="binary"?_buf:buf?buf:new BufferClass(16);var i=buf&&offset||0;var r=Math.random()*b32;b[i++]=r&ff;b[i++]=r>>>8&ff;b[i++]=r>>>16&ff;b[i++]=r>>>24&ff;r=Math.random()*b32;b[i++]=r&ff;b[i++]=r>>>8&ff;b[i++]=r>>>16&15|64;b[i++]=r>>>24&
ff;r=Math.random()*b32;b[i++]=r&63|128;b[i++]=r>>>8&ff;b[i++]=r>>>16&ff;b[i++]=r>>>24&ff;r=Math.random()*b32;b[i++]=r&ff;b[i++]=r>>>8&ff;b[i++]=r>>>16&ff;b[i++]=r>>>24&ff;return fmt===undefined?unparse(b):b}uuid.parse=parse;uuid.unparse=unparse;uuid.BufferClass=BufferClass;if(typeof module!="undefined")module.exports=uuid;else this.uuid=uuid}).call(window);var u=Bootstrapper.Cookies.get("_ensUUID");if(u==undefined||!u){u=window.uuid();var d=new Date;d.setTime(d.getTime()+1E3*60*60*24*365.25*4);Bootstrapper.Cookies.set("_ensUUID",
u,d)}else{var d=new Date;d.setTime(d.getTime()+1E3*60*60*24*365.25*4);Bootstrapper.Cookies.set("_ensUUID",u,d)}Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(n.length){for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));
for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}()},457978,255720);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTracker=function(){var _private={links:{},pushTrack:function(name,fn){if(typeof name!="string")return false;this.links[name]=this.links[name]||[];if(typeof fn=="function")this.links[name].push(fn);return true},callTrack:function(name){if(typeof name!="string")return false;var l=_private.links[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)}},
_public={addLink:function(name,fn){return _private.pushTrack(name,fn)},addTracking:function(name,fn){return _private.pushTrack(name,fn)},getLink:function(name){return _private.links[name]},track:function(name){return _private.callTrack.call(this,name)}};return _public}();Bootstrapper.attachLink=function(node,name,event){if(node==undefined||node==null||typeof name!="string")return false;event=event||"onclick";Bootstrapper.unobtrusiveAddEvent(node,event,function(){Bootstrapper.linkTracker.track.call(this,
name)})}},457200,255710);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=
path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=
window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=
b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},
i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:false||!!~window.location.search.indexOf("ensCloak\x3ddisable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3dsync"),pageSpecificCompletion:true,content:{map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+=
"##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL utils not available")}else{if(Bootstrapper.MVT.EDLutils)_log("*** Cloak:EDL not available");Bootstrapper.MVT.EDLutils=false}},store:function(o){this.list=o;this.utils("set",
"_ensCloak",o);_log("*** Cloak:Storage updated")},load:function(d){var cl=this.utils("get","_ensCloak")||this.list;if(!d)_log(cl);if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&
o.x!=""){this.map[o.x]=o;this.map[o.x].t="map"}else Bootstrapper.MVT.invisibilityCloak=true}else{this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){var sync=this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if((fetch||Bootstrapper.MVT.forceSyncCloak)&&!Bootstrapper.MVT.cloakDisabled){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]=
"sync";Bootstrapper.MVT.invisibilityCloak=true;_log("*** Cloak:Syncing")}this.load(1);var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,
a,b)},init:function(){Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");_log(h.tests.slice());Bootstrapper.MVT.initialized=!0;if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;if(this.pageSpecificCompletion)Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},
500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);
this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");
this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");if(this.pageSpecificCompletion)Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=
!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);_log("*** Cloak: "+x);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&b.cloak){this.delCSS(b.cloak);_log("*** Cloak:Showing "+b.x)}else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=
this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);if(typeof Bootstrapper.MVT.alldone=="undefined"){Bootstrapper.MVT.alldone=1;_log("*** Cloak:done");_log("*** MVT:done")}},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},
25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,
b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,c[0]):h.split(c,b)},onWTOError:function(evt){var error="invalid";try{if(evt)error=evt.name+"_"+evt.state}catch(e){}var meta=document.createElement("meta");meta.name="wtoexp";meta.content=error;document.getElementsByTagName("head")[0].appendChild(meta)},setWTOEvents:function(){if(typeof WTOptimize=="undefined")setTimeout(function(){Bootstrapper.MVT.setWTOEvents()},
10);else{WTOptimize.addEventHandler(WTEvent.INVALID,Bootstrapper.MVT.onWTOError);WTOptimize.addEventHandler(WTEvent.ABORT,Bootstrapper.MVT.onWTOError);WTOptimize.addEventHandler(WTEvent.DONE,null,Bootstrapper.MVT.onWTOError);WTOptimize.addEventHandler(WTEvent.PAGEVIEW,null,Bootstrapper.MVT.onWTOError)}},isValidTestPage:function(pageArray,REGEX_Domain){var urlpath=window.location.pathname;var querystr=window.location.search;var isqueryexcl,isqueryincl;var _isTp=false;for(var i=0;i<pageArray.length;i++){isqueryexcl=
pageArray[i].e?pageArray[i].e.test(querystr):false;isqueryincl=pageArray[i].i?pageArray[i].i.test(querystr):true;if(pageArray[i].r.test(urlpath)&&!isqueryexcl&&isqueryincl)_isTp=true}return REGEX_Domain.r.test(document.URL)&&_isTp},isTestmode:function(REGEX_Domain){return REGEX_Domain.r.test(document.URL)&&~window.location.href.indexOf("testmode\x3dtrue")}};return i}();Bootstrapper._getServerComponent=Bootstrapper.getServerComponent;Bootstrapper.getServerComponent=function(){Bootstrapper.MVT.init();
Bootstrapper._getServerComponent.apply(Bootstrapper,arguments)};Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=
Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");
d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=
d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});var ns=window[ensightenOptions.ns];ns.VTconfig=ns.VTconfig||{};ns.VTconfig["MVT"]=this.deploymentId;Bootstrapper.MVT._traverse=Bootstrapper.MVT.traverse;Bootstrapper.MVT.traverse=function(b,a,c){if(document.body&&
typeof WTOptimize!="undefined"&&c.length>1)for(i=0;i<c.length;i++)if(c[i].t=="wt"){Bootstrapper.MVT.swap(b,c[i]);c.splice(i,1)}Bootstrapper.MVT._traverse(b,a,c)};Bootstrapper.MVT.addModule("wt",{init:function(a){if(typeof Bootstrapper.MVT.capi=="undefined"){document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+a.base+'"\x3e\x3c/sc'+"ript\x3e");Bootstrapper.MVT.capi=1}if(typeof Bootstrapper.MVT.wtCloak=="undefined")Bootstrapper.MVT.wtCloak=Bootstrapper.MVT.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}")},
swap:function(a,b){if(typeof WTOptimize=="undefined")setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);else{b.o=b.o||{};b.p=b.p||{};var dbg=~window.location.href.indexOf("ensightenDebug")?true:false,isE=function(o){for(i in o)return false;return true},ta=typeof b.a!="undefined"&&b.a!=""?'"'+b.a+'",':"",pobj="",n=navigator.userAgent||navigator.vendor||window.opera,p=!!n.match(/MSIE 6|MSIE 7|MSIE 8/i)?2E3:0;Bootstrapper.MVT.wtime=Bootstrapper.MVT.wtime||4E3+p;if(dbg)console.log("swap: "+(b.a||"testAlias undefined"));
if(typeof Bootstrapper.MVT.wtdone=="undefined"){Bootstrapper.MVT.isMobile=function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4)))return true;else return false}(n);if(dbg){Bootstrapper.time=(new Date).getTime();console.log("* WTO initiated : "+Bootstrapper.time)}var addHandler=function(e){WTOptimize.addEventHandler(WTEvent[e],function(event){if(e=="HIDESHOW"&&event.params.display)Bootstrapper.MVT.delCSS(Bootstrapper.MVT.wtCloak);else if(e!=="HIDESHOW")Bootstrapper.MVT.delCSS(Bootstrapper.MVT.wtCloak);if(dbg){var time=(new Date).getTime();console.log("* WTO "+e+" : "+time+" | elapsed:"+(parseInt(time)-parseInt(Bootstrapper.time)));
Bootstrapper.time=time}})},onE=["DONE","INVALID","ABORT"];if(Bootstrapper.MVT.hidden.length<2)onE.push("HIDESHOW");for(i=0;i<onE.length;i++)addHandler(onE[i]);Bootstrapper.MVT.wtime=Bootstrapper.MVT.isMobile?2E4:typeof b.o["s_pageTimeout"]!="undefined"?b.o["s_pageTimeout"]:Bootstrapper.MVT.wtime;setTimeout(function(){Bootstrapper.MVT.delCSS(Bootstrapper.MVT.wtCloak)},Bootstrapper.MVT.wtime);Bootstrapper.MVT.wtdone=1}if(!isE(b.p))b.o["data"]=b.p;b.o["s_pageTimeout"]=Bootstrapper.MVT.wtime;if(dbg){for(i in b.o)if(typeof b.o[i]==
"object"){pobj+=","+i+":{";for(j in b.o[i])pobj+=',"'+j+'":"'+b.o[i][j]+'"';pobj+="}"}else pobj+=","+i+':"'+b.o[i]+'"';pobj=pobj.replace(/\{\,/g,"{");console.log(("* WTOptimize.setup("+ta+"{"+(pobj!=""?pobj:"")+"});").replace(/\{\,/g,"{")+" # "+(new Date).getTime())}eval("WTOptimize.setup("+ta+"b.o)")}}});Bootstrapper.MVT.WTOconversion=function(b){b.o=b.o||{};b.p=b.p||{};var dbg=~window.location.href.indexOf("ensightenDebug")?true:false,isE=function(o){for(i in o)return false;return true},ta=typeof b.a!=
"undefined"&&b.a!=""?'"'+b.a+'",':"",pobj="";if(typeof Bootstrapper.MVT.capi=="undefined"){var s=document.createElement("script");s.type="text/javascript";s.src=b.base;document.getElementsByTagName("head")[0].appendChild(s);Bootstrapper.MVT.capi=1}if(typeof WTOptimize=="undefined")setTimeout(function(){Bootstrapper.MVT.WTOconversion(b)},10);else{if(!isE(b.p))b.o["data"]=b.p;b.o["conversionPoint"]="header";b.o["beacon"]=true;b.o["cookieInspection"]=false;WTOptimize.addEventHandler(WTEvent["PAGEVIEW"],
function(event){Bootstrapper.MVT.wtPageView=1;if(dbg){for(i in b.o)if(typeof b.o[i]=="object"){pobj+=","+i+":{";for(j in b.o[i])pobj+=',"'+j+'":"'+b.o[i][j]+'"';pobj+="}"}else pobj+=","+i+':"'+b.o[i]+'"';pobj=pobj.replace(/\{\,/g,"{");console.log(("* WTOptimize.conversion("+ta+"{"+(pobj!=""?pobj:"")+"});").replace(/\{\,/g,"{")+" # "+(new Date).getTime())}eval("WTOptimize.conversion("+ta+"b.o)")});if(typeof Bootstrapper.MVT.wtConversion=="undefined"){Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){if(typeof Bootstrapper.MVT.wtPageView==
"undefined"){var c=function(){for(i in WTOptimize)if(typeof WTOptimize[i]["s_eventHandlers"]!="undefined")return i;return""}();try{var px=WTOptimize[c].s_eventHandlers.pageview.success;for(i=0,l=px.length;i<l;i++)px[i].call(window)}catch(e){if(dbg)console.log("* WTOptimize Conversion Error *")}}},250)});Bootstrapper.MVT.wtConversion=1}}};Bootstrapper.MVT.addModule("tt",{init:function(){window.mboxWrite=function(a,b){var n=document.getElementById(a);if(n!==null)n.innerHTML+=b}},swap:function(a,b){if(typeof mboxFactoryDefault==
"undefined"||!mboxFactoryDefault.isEnabled()){Bootstrapper.MVT.show(a,b);_log("*** MVT:show - T\x26T disabled");_log(a);_log(b)}else{_log("*** MVT:loaded");_log(a);_log(b);var i="_ensMbox"+(1E3*Math.random()).toFixed(0),f,p,s,o=!1;if(b.a=="replace"){o=!0;if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA|BR/)){s=Bootstrapper.MVT.injectCSS("#"+i+"{visibility:hidden!important}",1);a.innerHTML='\x3cdiv id\x3d"'+i+'" class\x3d"mboxDefault"\x3e'+a.innerHTML+"\x3c/div\x3e"}else{b.a="element";setTimeout(function(){Bootstrapper.MVT.swap(a,
b)},1);return}}else{d=document.createElement("div");d.id=i;d.className="mboxDefault";d.style.visibility="hidden";if(b.a=="prepend"){if(a.firstChild!==null)a.insertBefore(d,a.firstChild);Bootstrapper.MVT.done()}else if(b.a=="append")a.appendChild(d,a);else if(b.a=="element"||typeof b.a=="undefined"){o=!0;var c=a.cloneNode(!0),s=Bootstrapper.MVT.injectCSS("#"+i+"{visibility:hidden!important}",1);d.appendChild(c);if(a.parentNode!==null)a.parentNode.replaceChild(d,a)}else if(b.a=="before"){if(a.parentNode!==
null)a.parentNode.insertBefore(d,a)}else if(b.a=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling)}Bootstrapper.MVT.show(a,b);f=b.p||{};p=[];for(k in f)p.push(k+"\x3d"+f[k]);var m=window.mboxDefine(i,b.i);p.unshift(b.i);window.mboxUpdate.apply(m,p);m=window.mboxFactories.get("default").get(b.i)||{};m._show=m.show;m._ens_init=!0;m.show=function(a,m,s){return function(){var r=m._show.call(m);if(r){m._ens_init=!1;clearTimeout(Bootstrapper["mboxTimeout_"+
m.g]);if(m.getDefaultDiv()&&m.getDefaultDiv().style)m.getDefaultDiv().style.visibility="visible";Bootstrapper.MVT.delCSS(s)}return r}}(a,m,s);m.ac=function(Fb,bc){if(!m._ens_init)if(Fb&&Fb.style)Fb.style.visibility=bc?"visible":"hidden";if(Fb&&Fb.style)Fb.style.display=bc?"block":"none"};Bootstrapper["mboxTimeout_"+m.g]=setTimeout(function(m){return function(){m.show=function(){};m.hide=function(){};if(m.getDefaultDiv()&&m.getDefaultDiv().style)m.getDefaultDiv().style.visibility="visible";Bootstrapper.MVT.done()}}(m),
25E3)}}})},770194,255984);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_CAPI_LOC="//smallbusiness.support.microsoft.com/AB/wt_capi.js";var REGEX_SSB_PROD={r:/\/smallbusiness\.support\.microsoft\.com/i};var REGEX_SSB_HOMEPG={r:/en-us(|\/|\/home(|\/))$/i};var REGEX_SSB_GLOBAL_HOMEPG={r:/\/[a-z]{2}-[a-z]{2}(|\/|\/home(|\/))$/i};var REGEX_SSB_CONTACT={r:/en-us\/contact(|\/)$/i};var REGEX_SSB_SEARCH_RESULTS={r:/en-us\/search|dynamicsearch(|\/)$/i};
var ssbPageArray=[REGEX_SSB_CONTACT,REGEX_SSB_GLOBAL_HOMEPG];var HTMLPATH="/HTML/BODY";Bootstrapper.MVT.isSSBTestPage=false;function isValidLang(){var isValidLangFlag=false;var urlpath=window.location.pathname;try{var langLoc=document.getElementsByTagName("html")[0].getAttribute("lang")||"";langLoc=langLoc.toLowerCase();isValidLangFlag=",en-us".indexOf(langLoc)>0;for(var i=0;i<ssbPageArray.length;i++)if(ssbPageArray[i].r.test(urlpath)){isValidLangFlag=true;break}}catch(e){}return isValidLangFlag}
if(Bootstrapper.MVT.isValidTestPage(ssbPageArray,REGEX_SSB_PROD)&&isValidLang()||Bootstrapper.MVT.isTestmode(REGEX_SSB_PROD)){Bootstrapper.MVT.isSSBTestPage=true;Bootstrapper.MVT.push({x:HTMLPATH,t:"wt",base:REGEX_CAPI_LOC,o:{"s_pageTimeout":6E3}});Bootstrapper.MVT.setWTOEvents()}else if(REGEX_SSB_PROD.r.test(document.URL))Bootstrapper.MVT.onWTOError(null)},770739,[770194],255868,[255984]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_CAPI_LOC="//mssmpotwb01.redmond.corp.microsoft.com/scripts/wt_capi.js";var REGEX_MPO_STG={r:/\/mssmpotwb01\.redmond\.corp\.microsoft\.com/i};var REGEX_MPO_INCIDENT_SUBMIT={r:/\/Incident\/Submit(|\/)$/i};var mpoTPageArray=[REGEX_MPO_STG];var HTMLPATH="/HTML/BODY";Bootstrapper.MVT.isMPOStagTestPage=false;function isValidLang(){var isValidLangFlag=true;
return isValidLangFlag}if(REGEX_MPO_STG.r.test(window.location.href)&&isValidLang()&&Bootstrapper.MVT.isTestmode(REGEX_MPO_STG)){Bootstrapper.MVT.isMPOStagTestPage=true;Bootstrapper.MVT.push({x:HTMLPATH,t:"wt",base:REGEX_CAPI_LOC,o:{"s_pageTimeout":6E3}});Bootstrapper.MVT.setWTOEvents()}else if(REGEX_MPO_STG.r.test(document.URL))Bootstrapper.MVT.onWTOError(null)},773778,[770194],304619,[255984]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var REGEX_DEV_TEST=/\/msssmctwb02\.redmond\.corp\.microsoft\.com/i;var REGEX_DEV_SMC=/support-uat\.microsoft\.com\/[a-z]{2}-[a-z]{2}\/contactus/i;function onWTOError(evt){var error="invalid";try{if(evt)error=evt.name+"_"+evt.state}catch(e){}var meta=document.createElement("meta");meta.name="wtoexp";meta.content=error;document.getElementsByTagName("head")[0].appendChild(meta)}
function setWTOEvents(){if(typeof WTOptimize=="undefined")setTimeout(function(){setWTOEvents()},10);else{WTOptimize.addEventHandler(WTEvent.INVALID,onWTOError);WTOptimize.addEventHandler(WTEvent.ABORT,onWTOError);WTOptimize.addEventHandler(WTEvent.DONE,null,onWTOError);WTOptimize.addEventHandler(WTEvent.PAGEVIEW,null,onWTOError)}}if(REGEX_DEV_TEST.test(document.URL))if(~window.location.href.indexOf("testmode\x3dtrue")){Bootstrapper.MVT.push({x:"/HTML/BODY",t:"wt",base:"//msssmctwb02.redmond.corp.microsoft.com/my/scripts/wt_capi.js",
o:{"s_pageTimeout":6E3}});setWTOEvents()}else onWTOError(null);if(REGEX_DEV_SMC.test(document.URL))if(~window.location.href.indexOf("testmode\x3dtrue")){Bootstrapper.MVT.push({x:"/HTML/BODY",t:"wt",base:"//support-uat.microsoft.com/my/scripts/wt_capi.js",o:{"s_pageTimeout":6E3}});setWTOEvents()}else onWTOError(null)},787980,256111);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();